/// List of background images for coaching screens
const List<String> backgroundImages = [
  'assets/images/backgrounds/291450-landscape-lake-Yellowstone_National_Park.jpeg',
  'assets/images/backgrounds/3c2fe6f8cf9fee3dbeb0e970f3ea2f4cf83f.jpg',
  'assets/images/backgrounds/504685-5k-uhd-gmunden-mountain-lake-bad-goisern-landscape.jpg',
  'assets/images/backgrounds/a-beautiful-landscape-from-terrace-sunrise-over-italy_5120x2880.jpg',
  'assets/images/backgrounds/across_the_little_lake_at_sunset-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/Bagan Sunset-X3.jpg',
  'assets/images/backgrounds/batmans_hideout-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/Beach At Night.jpg',
  'assets/images/backgrounds/beautiful_sunset_lake-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/beautiful-house-reflection-on-water-surrounded-by-green-grass-and-trees-4k-5k-nature.jpg',
  'assets/images/backgrounds/boat_4-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/boat-5120x2880-lake-mountains-vacation-norway-4k-16560.jpg',
  'assets/images/backgrounds/breaking_dawn-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/breathtaking_view-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/claudio-testa-150192-unsplash.jpg',
  'assets/images/backgrounds/colorful_light_2-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/DSC_0048.JPG',
  'assets/images/backgrounds/emerald_lake_in_banff_national_park_5k-5120x2880.jpg',
  'assets/images/backgrounds/feel_the_moment-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/fog_at_the_pink_house-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/Frosty Lake.jpg',
  'assets/images/backgrounds/Fuji2.jpg',
  'assets/images/backgrounds/golden_sunset_light-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/hallstatter-see-5120x2880-lake-austria-5k-3562.jpg',
  'assets/images/backgrounds/halstatt.jpg',
  'assets/images/backgrounds/hidden_lake-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/hidden_reflection-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/high_alpine_landscape-wallpaper-5120x2880.jpg',
  'assets/images/backgrounds/horizon-lake-nature-reflection-sunset-tree-image-5120x2880.jpg',
  'assets/images/backgrounds/house-5120x2880-lake-trees-winter-5k-17375.jpg',
];


